### ISSUE TITLE
Wrong class selector example

### ISSUE THREAD

**Issue by idmarjr** [ArthurMota9/css-specificity#1]
This is the statement you have in this slide:
> Selects all elements with class="myClass2" that is a descendant of an element with class="myClass" 

https://github.com/ArthurMota9/css-specificity/blob/6ba4413ed2d0cc05737089897cb6248f523a0e13/index.html#L178-L193

In order to this be true, you should not have the comma here: `.myClass, .myClass2`

**Comment by ArthurMota9** [comment]
@idmarjr Thanks for your help! [Fixed here.](https://github.com/ArthurMota9/css-specificity/commit/1550e150a96aef0ef8a638b6e4c82305ceb996bc)
